package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

func writeSARIF(t *testing.T, content string) string {
	t.Helper()
	f, err := os.CreateTemp(t.TempDir(), "*.sarif")
	require.NoError(t, err)
	_, err = f.WriteString(content)
	require.NoError(t, err)
	require.NoError(t, f.Close())
	return f.Name()
}

func TestParseSARIF_Empty(t *testing.T) {
	path := writeSARIF(t, `{"runs":[]}`)
	report, err := parseSARIF(path)
	require.NoError(t, err)
	require.Empty(t, report.findings())
}

func TestParseSARIF_Missing(t *testing.T) {
	_, err := parseSARIF(filepath.Join(t.TempDir(), "nofile.sarif"))
	require.Error(t, err)
}

func TestParseSARIF_Basic(t *testing.T) {
	sarif := `{
		"runs": [{
			"tool": {"driver": {"name": "mytool", "informationUri": "https://example.com", "rules": [
				{"id": "R001", "helpUri": "https://example.com/R001"}
			]}},
			"results": [{
				"ruleId": "R001",
				"level": "warning",
				"message": {"text": "something bad"},
				"locations": [{"physicalLocation": {"artifactLocation": {"uri": "foo/bar.go"}, "region": {"startLine": 42}}}]
			}]
		}]
	}`
	report, err := parseSARIF(writeSARIF(t, sarif))
	require.NoError(t, err)
	findings := report.findings()
	require.Len(t, findings, 1)
	f := findings[0]
	require.Equal(t, "mytool", f.tool)
	require.Equal(t, "https://example.com", f.toolURI)
	require.Equal(t, "R001", f.ruleID)
	require.Equal(t, "https://example.com/R001", f.ruleURI)
	require.Equal(t, "warning", f.level)
	require.Equal(t, "something bad", f.message)
	require.Equal(t, "foo/bar.go", f.path)
	require.Equal(t, 42, f.line)
}

func TestParseSARIF_DefaultsLevelToWarning(t *testing.T) {
	sarif := `{"runs": [{"tool": {"driver": {"name": "t"}}, "results": [{"ruleId": "X", "message": {"text": "m"}}]}]}`
	report, err := parseSARIF(writeSARIF(t, sarif))
	require.NoError(t, err)
	require.Equal(t, "warning", report.findings()[0].level)
}

func TestParseSARIF_NoLocation(t *testing.T) {
	sarif := `{"runs": [{"tool": {"driver": {"name": "t"}}, "results": [{"ruleId": "X", "level": "error", "message": {"text": "m"}, "locations": []}]}]}`
	report, err := parseSARIF(writeSARIF(t, sarif))
	require.NoError(t, err)
	require.Empty(t, report.findings()[0].path)
	require.Zero(t, report.findings()[0].line)
}

func TestMarkdown_Empty(t *testing.T) {
	require.Empty(t, (sarifReport{}).Markdown())
}

func TestMarkdown_SingleRun(t *testing.T) {
	report := sarifReport{Runs: []sarifRun{{
		Tool: sarifTool{Driver: sarifDriver{
			Name:           "lint",
			InformationURI: "https://lint.dev",
			Rules:          []sarifRule{{ID: "R1", HelpURI: "https://lint.dev/R1"}},
		}},
		Results: []sarifResult{
			{
				RuleID:  "R1",
				Level:   "error",
				Message: sarifMessage{Text: "bad"},
				Locations: []sarifLocation{{
					PhysicalLocation: sarifPhysicalLocation{
						ArtifactLocation: sarifArtifactLocation{URI: "a.go"},
						Region:           sarifRegion{StartLine: 1},
					},
				}},
			},
			{
				RuleID:  "R2",
				Level:   "warning",
				Message: sarifMessage{Text: "meh"},
				Locations: []sarifLocation{{
					PhysicalLocation: sarifPhysicalLocation{
						ArtifactLocation: sarifArtifactLocation{URI: "b.go"},
						Region:           sarifRegion{StartLine: 5},
					},
				}},
			},
		},
	}}}
	out := report.Markdown()
	require.Contains(t, out, "[lint](https://lint.dev)")
	require.Contains(t, out, ":no_entry: 1 error")
	require.Contains(t, out, ":warning: 1 warning")
	require.Contains(t, out, "[R1](https://lint.dev/R1)")
	require.Contains(t, out, "R2")
	require.Contains(t, out, "`a.go:1`")
	require.Contains(t, out, "_Generated by sarif-annotate_")
}

func TestMarkdown_MultiRun(t *testing.T) {
	report := sarifReport{Runs: []sarifRun{
		{
			Tool:    sarifTool{Driver: sarifDriver{Name: "toolA"}},
			Results: []sarifResult{{RuleID: "A1", Level: "warning", Message: sarifMessage{Text: "a"}}},
		},
		{
			Tool:    sarifTool{Driver: sarifDriver{Name: "toolB"}},
			Results: []sarifResult{{RuleID: "B1", Level: "error", Message: sarifMessage{Text: "b"}}},
		},
	}}
	out := report.Markdown()
	require.Contains(t, out, "### toolA")
	require.Contains(t, out, "### toolB")
	idxA := strings.Index(out, "### toolA")
	idxB := strings.Index(out, "### toolB")
	require.Less(t, idxA, idxB, "toolA section should appear before toolB")
}

func TestMarkdown_PipeEscaped(t *testing.T) {
	report := sarifReport{Runs: []sarifRun{{
		Tool:    sarifTool{Driver: sarifDriver{Name: "t"}},
		Results: []sarifResult{{RuleID: "X", Level: "warning", Message: sarifMessage{Text: "use a|b instead"}}},
	}}}
	out := report.Markdown()
	require.Contains(t, out, `a\|b`)
}
