package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"strings"
	"text/template"
)

type sarifReport struct {
	Runs []sarifRun `json:"runs"`
}

type sarifRun struct {
	Tool    sarifTool     `json:"tool"`
	Results []sarifResult `json:"results"`
}

type sarifTool struct {
	Driver sarifDriver `json:"driver"`
}

type sarifDriver struct {
	Name           string      `json:"name"`
	InformationURI string      `json:"informationUri"`
	Rules          []sarifRule `json:"rules"`
}

type sarifRule struct {
	ID      string `json:"id"`
	HelpURI string `json:"helpUri"`
}

type sarifResult struct {
	RuleID    string          `json:"ruleId"`
	Level     string          `json:"level"`
	Message   sarifMessage    `json:"message"`
	Locations []sarifLocation `json:"locations"`
}

type sarifMessage struct {
	Text string `json:"text"`
}

type sarifLocation struct {
	PhysicalLocation sarifPhysicalLocation `json:"physicalLocation"`
}

type sarifPhysicalLocation struct {
	ArtifactLocation sarifArtifactLocation `json:"artifactLocation"`
	Region           sarifRegion           `json:"region"`
}

type sarifArtifactLocation struct {
	URI string `json:"uri"`
}

type sarifRegion struct {
	StartLine int `json:"startLine"`
}

type finding struct {
	tool    string
	toolURI string
	ruleID  string
	ruleURI string
	level   string
	message string
	path    string
	line    int
}

type markdownGroup struct {
	ToolLabel string
	Pills     string
	Rows      []markdownRow
}

type markdownRow struct {
	Icon     string
	Level    string
	Rule     string
	Location string
	Message  string
}

const generatedBy = "sarif-annotate"

const markdownTemplate = `{{range .Groups}}
### {{.ToolLabel}}

{{.Pills}}

| Severity | Rule | Location | Message |
|----------|------|----------|---------|
{{range .Rows}}| {{.Icon}} {{.Level}} | {{.Rule}} | {{.Location}} | {{.Message}} |
{{end}}
{{end}}
---
_Generated by {{.GeneratedBy}}_`

var markdownTmpl = template.Must(template.New("markdown").Parse(markdownTemplate))

func main() {
	flag.Usage = func() {
		fmt.Fprintf(os.Stderr, "usage: sarif-annotate <sarif-file>\n")
		flag.PrintDefaults()
	}
	flag.Parse()

	if flag.NArg() != 1 {
		flag.Usage()
		os.Exit(1)
	}

	report, err := parseSARIF(flag.Arg(0))
	if err != nil {
		fmt.Fprintf(os.Stderr, "sarif-annotate: %v\n", err)
		os.Exit(1)
	}

	if md := report.Markdown(); md != "" {
		fmt.Print(md)
	}
}

func parseSARIF(path string) (sarifReport, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return sarifReport{}, fmt.Errorf("reading %s: %w", path, err)
	}

	var report sarifReport
	if err := json.Unmarshal(data, &report); err != nil {
		return sarifReport{}, fmt.Errorf("parsing %s: %w", path, err)
	}

	return report, nil
}

func (r sarifReport) findings() []finding {
	var findings []finding
	for _, run := range r.Runs {
		tool := run.Tool.Driver.Name
		toolURI := run.Tool.Driver.InformationURI
		ruleURIs := make(map[string]string, len(run.Tool.Driver.Rules))
		for _, rule := range run.Tool.Driver.Rules {
			ruleURIs[rule.ID] = rule.HelpURI
		}
		for _, res := range run.Results {
			level := res.Level
			if level == "" {
				level = "warning"
			}
			f := finding{
				tool:    tool,
				toolURI: toolURI,
				ruleID:  res.RuleID,
				ruleURI: ruleURIs[res.RuleID],
				level:   level,
				message: res.Message.Text,
			}
			if len(res.Locations) > 0 {
				loc := res.Locations[0].PhysicalLocation
				f.path = loc.ArtifactLocation.URI
				f.line = loc.Region.StartLine
			}
			findings = append(findings, f)
		}
	}
	return findings
}

func (r sarifReport) Markdown() string {
	findings := r.findings()
	if len(findings) == 0 {
		return ""
	}

	// group by tool so multi-run SARIF files get one section per tool
	type group struct {
		tool    string
		toolURI string
		items   []finding
	}
	var grouped []group
	idx := map[string]int{}
	for _, f := range findings {
		i, ok := idx[f.tool]
		if !ok {
			i = len(grouped)
			idx[f.tool] = i
			grouped = append(grouped, group{tool: f.tool, toolURI: f.toolURI})
		}
		grouped[i].items = append(grouped[i].items, f)
	}

	var groups []markdownGroup
	for _, g := range grouped {
		mg := markdownGroup{
			ToolLabel: toolLabel(g.tool, g.toolURI),
			Pills:     buildPills(g.items),
		}
		for _, f := range g.items {
			mg.Rows = append(mg.Rows, markdownRow{
				Icon:     levelIcon(f.level),
				Level:    f.level,
				Rule:     ruleLink(f.ruleID, f.ruleURI),
				Location: location(f.path, f.line),
				Message:  strings.ReplaceAll(f.message, "|", "\\|"),
			})
		}
		groups = append(groups, mg)
	}

	var buf bytes.Buffer
	if err := markdownTmpl.Execute(&buf, struct {
		Groups      []markdownGroup
		GeneratedBy string
	}{groups, generatedBy}); err != nil {
		panic(fmt.Sprintf("markdown template: %v", err))
	}
	return buf.String()
}

func toolLabel(tool, toolURI string) string {
	if toolURI != "" {
		return fmt.Sprintf("[%s](%s)", tool, toolURI)
	}
	return tool
}

func buildPills(items []finding) string {
	counts := map[string]int{}
	for _, f := range items {
		counts[f.level]++
	}
	var pills []string
	for _, lvl := range []string{"error", "warning", "note"} {
		if n := counts[lvl]; n > 0 {
			pills = append(pills, fmt.Sprintf("%s %d %s", levelIcon(lvl), n, pluralise(lvl, n)))
		}
	}
	return strings.Join(pills, " · ")
}

func location(path string, line int) string {
	if path == "" {
		return ""
	}
	if line > 0 {
		return fmt.Sprintf("`%s:%d`", path, line)
	}
	return fmt.Sprintf("`%s`", path)
}

func ruleLink(ruleID, ruleURI string) string {
	if ruleURI != "" {
		return fmt.Sprintf("[%s](%s)", ruleID, ruleURI)
	}
	return ruleID
}

func levelIcon(level string) string {
	switch level {
	case "error":
		return ":no_entry:"
	case "warning":
		return ":warning:"
	default:
		return ":information_source:"
	}
}

func pluralise(word string, n int) string {
	if n == 1 {
		return word
	}
	return word + "s"
}
