package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

func writeJUnit(t *testing.T, content string) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), "junit.xml")
	require.NoError(t, os.WriteFile(path, []byte(content), 0o600))
	return path
}

func TestParseJUnit_GotestSumFailure(t *testing.T) {
	path := writeJUnit(t, `<testsuites tests="1" failures="1">
		<testsuite name="github.com/example/project/internal/store" tests="1" failures="1">
			<testcase classname="github.com/example/project/internal/store" name="TestUpsert" time="0.110000">
				<failure message="Failed" type="">store_test.go:12: metadata was changed&#xA;--- FAIL: TestUpsert</failure>
			</testcase>
		</testsuite>
	</testsuites>`)
	report, err := parseJUnit(path)
	require.NoError(t, err)
	require.Equal(t, []failure{{
		Suite: "github.com/example/project/internal/store", ClassName: "github.com/example/project/internal/store",
		Name: "TestUpsert", Time: "0.110000", Kind: "failure", Message: "Failed",
		Body: "store_test.go:12: metadata was changed\n--- FAIL: TestUpsert",
	}}, report.failures())
}

func TestParseJUnit_StandaloneSuiteAndError(t *testing.T) {
	report, err := parseJUnit(writeJUnit(t, `<testsuite name="pkg"><testcase name="TestBoom"><error message="panic" type="runtime">stack</error></testcase></testsuite>`))
	require.NoError(t, err)
	failures := report.failures()
	require.Len(t, failures, 1)
	require.Equal(t, "error", failures[0].Kind)
	require.Equal(t, "runtime", failures[0].Type)
}

func TestParseJUnit_NestedSuites(t *testing.T) {
	report, err := parseJUnit(writeJUnit(t, `<testsuites><testsuite name="parent"><testsuite name="child"><testcase name="TestNested"><failure>bad</failure></testcase></testsuite></testsuite></testsuites>`))
	require.NoError(t, err)
	require.Equal(t, "parent/child", report.failures()[0].Suite)
}

func TestParseJUnit_MissingAndMalformed(t *testing.T) {
	_, err := parseJUnit(filepath.Join(t.TempDir(), "missing.xml"))
	require.Error(t, err)
	_, err = parseJUnit(writeJUnit(t, `<testsuites>`))
	require.Error(t, err)
	_, err = parseJUnit(writeJUnit(t, `<report/>`))
	require.Error(t, err)
}

func TestMarkdown_NoFailures(t *testing.T) {
	require.Empty(t, (testSuites{}).Markdown(defaultMaxFailures))
}

func TestMarkdown_RendersFailure(t *testing.T) {
	report := testSuites{Suites: []testSuite{{Name: "suite", Cases: []testCase{{
		ClassName: "example/pkg", Name: "TestBad", Time: "0.25",
		Failure: &testFailure{Message: "wanted *x*", Type: "assertion", Body: "line 1\nline 2"},
	}}}}}
	out := report.Markdown(defaultMaxFailures)
	require.Contains(t, out, "### :x: 1 failed test")
	require.Contains(t, out, "`example/pkg.TestBad`")
	require.Contains(t, out, "result: `failure`")
	require.Contains(t, out, "duration: `0.25s`")
	require.Contains(t, out, "type: `assertion`")
	require.Contains(t, out, `wanted \*x\*`)
	require.Contains(t, out, "    line 1\n    line 2")
	require.Contains(t, out, "_Generated by junit-annotate_")
}

func TestMarkdown_LimitsAndTruncatesFailures(t *testing.T) {
	report := testSuites{Suites: []testSuite{{Name: "suite", Cases: []testCase{
		{Name: "TestOne", Failure: &testFailure{Body: strings.Repeat("x", maxFailureRunes+1)}},
		{Name: "TestTwo", Error: &testFailure{Body: "boom"}},
	}}}}
	out := report.Markdown(1)
	require.Contains(t, out, "2 failed tests")
	require.Contains(t, out, "output truncated")
	require.Contains(t, out, "1 more failure omitted")
	require.NotContains(t, out, "TestTwo")
}
