package main

import (
	"encoding/xml"
	"flag"
	"fmt"
	"os"
	"strings"
	"unicode/utf8"
)

const (
	defaultMaxFailures = 20
	maxFailureRunes    = 4000
	generatedBy        = "junit-annotate"
)

type testSuites struct {
	Suites []testSuite `xml:"testsuite"`
}

type testSuite struct {
	Name   string      `xml:"name,attr"`
	Suites []testSuite `xml:"testsuite"`
	Cases  []testCase  `xml:"testcase"`
}

type testCase struct {
	ClassName string       `xml:"classname,attr"`
	Name      string       `xml:"name,attr"`
	Time      string       `xml:"time,attr"`
	Failure   *testFailure `xml:"failure"`
	Error     *testFailure `xml:"error"`
}

type testFailure struct {
	Message string `xml:"message,attr"`
	Type    string `xml:"type,attr"`
	Body    string `xml:",chardata"`
}

type failure struct {
	Suite     string
	ClassName string
	Name      string
	Time      string
	Kind      string
	Message   string
	Type      string
	Body      string
}

func main() {
	maxFailures := flag.Int("max-failures", defaultMaxFailures, "maximum failures to render")
	flag.Usage = func() {
		fmt.Fprintf(os.Stderr, "usage: junit-annotate [flags] <junit-file>\n")
		flag.PrintDefaults()
	}
	flag.Parse()
	if flag.NArg() != 1 || *maxFailures < 1 {
		flag.Usage()
		os.Exit(1)
	}

	report, err := parseJUnit(flag.Arg(0))
	if err != nil {
		fmt.Fprintf(os.Stderr, "junit-annotate: %v\n", err)
		os.Exit(1)
	}
	if md := report.Markdown(*maxFailures); md != "" {
		fmt.Print(md)
	}
}

func parseJUnit(path string) (testSuites, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return testSuites{}, fmt.Errorf("reading %s: %w", path, err)
	}

	var root struct {
		XMLName xml.Name
	}
	if err := xml.Unmarshal(data, &root); err != nil {
		return testSuites{}, fmt.Errorf("parsing %s: %w", path, err)
	}

	var report testSuites
	switch root.XMLName.Local {
	case "testsuites":
		if err := xml.Unmarshal(data, &report); err != nil {
			return testSuites{}, fmt.Errorf("parsing %s: %w", path, err)
		}
	case "testsuite":
		var suite testSuite
		if err := xml.Unmarshal(data, &suite); err != nil {
			return testSuites{}, fmt.Errorf("parsing %s: %w", path, err)
		}
		report.Suites = []testSuite{suite}
	default:
		return testSuites{}, fmt.Errorf("parsing %s: unsupported root element %q", path, root.XMLName.Local)
	}
	return report, nil
}

func (r testSuites) failures() []failure {
	var failures []failure
	for _, suite := range r.Suites {
		failures = append(failures, suite.failures("")...)
	}
	return failures
}

func (s testSuite) failures(parent string) []failure {
	suiteName := s.Name
	if parent != "" {
		suiteName = parent + "/" + s.Name
	}
	var failures []failure
	for _, tc := range s.Cases {
		if tc.Failure != nil {
			failures = append(failures, newFailure(suiteName, tc, "failure", tc.Failure))
		}
		if tc.Error != nil {
			failures = append(failures, newFailure(suiteName, tc, "error", tc.Error))
		}
	}
	for _, child := range s.Suites {
		failures = append(failures, child.failures(suiteName)...)
	}
	return failures
}

func newFailure(suite string, tc testCase, kind string, detail *testFailure) failure {
	return failure{
		Suite: suite, ClassName: tc.ClassName, Name: tc.Name, Time: tc.Time,
		Kind: kind, Message: detail.Message, Type: detail.Type, Body: strings.TrimSpace(detail.Body),
	}
}

func (r testSuites) Markdown(maxFailures int) string {
	failures := r.failures()
	if len(failures) == 0 {
		return ""
	}
	shown := min(len(failures), maxFailures)

	var b strings.Builder
	fmt.Fprintf(&b, "### :x: %d failed test%s\n\n", len(failures), plural(len(failures)))
	for _, f := range failures[:shown] {
		fmt.Fprintf(&b, "#### `%s`\n\n", escapeCode(f.label()))
		metadata := []string{"result: `" + escapeCode(f.Kind) + "`"}
		if f.Time != "" {
			metadata = append(metadata, "duration: `"+escapeCode(f.Time)+"s`")
		}
		if f.Type != "" {
			metadata = append(metadata, "type: `"+escapeCode(f.Type)+"`")
		}
		if len(metadata) > 0 {
			b.WriteString(strings.Join(metadata, " · ") + "\n\n")
		}
		if f.Message != "" && f.Message != "Failed" {
			fmt.Fprintf(&b, "> %s\n\n", escapeMarkdown(f.Message))
		}
		if f.Body != "" {
			b.WriteString("<details><summary>Failure output</summary>\n\n")
			b.WriteString(indent(truncate(f.Body, maxFailureRunes)))
			b.WriteString("\n\n</details>\n\n")
		}
	}
	if omitted := len(failures) - shown; omitted > 0 {
		fmt.Fprintf(&b, "_…and %d more failure%s omitted._\n\n", omitted, plural(omitted))
	}
	fmt.Fprintf(&b, "---\n_Generated by %s_", generatedBy)
	return b.String()
}

func (f failure) label() string {
	name := f.Name
	if f.ClassName != "" {
		name = f.ClassName + "." + name
	} else if f.Suite != "" {
		name = f.Suite + "." + name
	}
	return name
}

func truncate(value string, maxRunes int) string {
	if utf8.RuneCountInString(value) <= maxRunes {
		return value
	}
	runes := []rune(value)
	return string(runes[:maxRunes]) + "\n… output truncated"
}

func indent(value string) string {
	lines := strings.Split(value, "\n")
	for i := range lines {
		lines[i] = "    " + lines[i]
	}
	return strings.Join(lines, "\n")
}

func escapeCode(value string) string {
	return strings.ReplaceAll(value, "`", "'")
}

func escapeMarkdown(value string) string {
	value = strings.ReplaceAll(value, "\n", " ")
	replacer := strings.NewReplacer("\\", "\\\\", "`", "\\`", "*", "\\*", "_", "\\_", "[", "\\[", "]", "\\]")
	return replacer.Replace(value)
}

func plural(count int) string {
	if count == 1 {
		return ""
	}
	return "s"
}
