image: "buildkite/hosted-agent-base-images:ubuntu-jammy"

steps:
  - group: ":mag: QA"
    key: quality_checks
    steps:
      - label: ":golangci-lint: lint"
        command: golangci-lint run --verbose --timeout 3m
        plugins:
          - mise#v1.1.1: ~

      - label: ":go: test"
        artifact_paths:
          - cover-tree.svg
          - coverage.out
        commands:
          - go test -coverprofile coverage.out -coverpkg=./... ./...
          - go run github.com/nikolaydubina/go-cover-treemap -coverprofile coverage.out > cover-tree.svg
          - echo '<details><summary>Coverage tree map</summary><img src="artifact://cover-tree.svg" alt="Test coverage tree map" width="70%"></details>' | buildkite-agent annotate --style "info"
        plugins:
          - mise#v1.1.1: ~