image: "buildkite/hosted-agent-base-images:ubuntu-jammy"

cache:
  name: "build-cache"
  paths:
    - "/gocache"
    - "/gomodcache"
  size: "100g"

steps:
  - group: ":mag: QA"
    key: quality_checks
    steps:
      - label: ":golangci-lint: lint"
        commands:
          - bun install --frozen-lockfile
          - bun run build
          - golangci-lint run --output.sarif.path golangci-lint.sarif --verbose --timeout 3m
        artifact_paths:
          - golangci-lint.sarif
        env:
          GOCACHE: /gocache
          GOMODCACHE: /gomodcache
        plugins:
          - mise#v1.1.4: ~
          - ./.buildkite/plugins/sarif-annotate:
              file: golangci-lint.sarif

      - label: ":terraform: lint"
        command: tflint --chdir=infra/terraform -f sarif > tflint.sarif
        artifact_paths:
          - tflint.sarif
        env:
          TFLINT_LOG: debug
        plugins:
          - mise#v1.1.4: ~
          - ./.buildkite/plugins/sarif-annotate:
              file: tflint.sarif

      - label: ":go: test"
        artifact_paths:
          - cover-tree.svg
          - coverage.out
          - junit.xml
        commands:
          - bun install --frozen-lockfile
          - bun run build
          - go run gotest.tools/gotestsum@latest --junitfile junit.xml --format testname -- -coverprofile=coverage.out ./...
        env:
          GOCACHE: /gocache
          GOMODCACHE: /gomodcache
        plugins:
          - mise#v1.1.4: ~
          - ./.buildkite/plugins/go-coverage:
              coverprofile: coverage.out
              treemap: true
              treemap-output: cover-tree.svg
          - ./.buildkite/plugins/junit-annotate:
              file: junit.xml
              context: go-tests
              max-failures: 20

      - label: ":bun: test and lint"
        commands:
          - bun install --frozen-lockfile
          - bun run test
          - bun run lint
        plugins:
          - mise#v1.1.4: ~
