image: "buildkite/hosted-agent-base-images:ubuntu-jammy"

cache:
  name: "build-cache"
  paths:
    - "/gocache"
    - "/gomodcache"
  size: "100g"

steps:
  - group: ":mag: QA"
    key: quality_checks
    steps:
      - label: ":golangci-lint: lint"
        command: golangci-lint run --output.checkstyle.path checkstyle.xml --verbose --timeout 3m
        artifact_paths:
          - checkstyle.xml
        env:
          GOCACHE: /gocache
          GOMODCACHE: /gomodcache
        plugins:
          - mise#v1.1.1: ~

      - label: ":go: test"
        artifact_paths:
          - cover-tree.svg
          - coverage.out
          - junit.xml
        commands:
          - go run gotest.tools/gotestsum@latest --junitfile junit.xml --format testname -- -coverprofile=coverage.out ./...
          - go run github.com/nikolaydubina/go-cover-treemap -coverprofile coverage.out > cover-tree.svg
          - echo '<details><summary>Coverage tree map</summary><img src="artifact://cover-tree.svg" alt="Test coverage tree map" width="70%"></details>' | buildkite-agent annotate --style "info"
        env:
          GOCACHE: /gocache
          GOMODCACHE: /gomodcache
        plugins:
          - mise#v1.1.1: ~